### ISSUE TITLE
Description language

### ISSUE THREAD

**Issue by razzeee** [flathub/com.hostbuf.FinalShell#3]
It would be good to separate out the japanese description to it's own translated version and not have it in the english one.
https://github.com/flathub/com.hostbuf.FinalShell/blob/master/com.hostbuf.FinalShell.metainfo.xml#L9

For e.g.
https://www.freedesktop.org/software/appstream/docs/chap-CatalogData.html#spec-asxml-example

So something like this should work:
```
 <description lang="jp">Translation</description>
```

**Comment by razzeee** [comment]
You can also markup the `<p>` statements like that. But I think that might not display correctly on the website right now. But should in software centers.

**Comment by jcleng** [comment]
i see there [tag-ct-languages](https://www.freedesktop.org/software/appstream/docs/chap-CatalogData.html#tag-ct-languages) and is Chinese use `zh`

**Comment by razzeee** [comment]
The website currently only handles English app texts

**Comment by jcleng** [comment]
@razzeee  https://github.com/flathub/com.hostbuf.FinalShell/blob/c66c08c0a88b30886f044288592953c6001692c7/com.hostbuf.FinalShell.metainfo.xml#L34 [https://flathub.org/apps/com.hostbuf.FinalShell](https://flathub.org/apps/com.hostbuf.FinalShell) Not effective

**Comment by razzeee** [comment]
Sorry, I think it needs to be

```
 <description xml:lang="zh"> 
```

**Comment by jcleng** [comment]
not effective for website, `xml:lang` or  `lang`, may be only  software centers of desktop.

**Comment by razzeee** [comment]
Looks good on the website now. Thx!
